//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray;

@interface Sequence : NSObject
{
    CDStruct_009559ee *events;
    unsigned int numEvent;
    unsigned int numPlayEvent;
    unsigned int endSector;
    char musicBar[60];
    unsigned int currentIndex;
    unsigned int currentHoldIndex;
    unsigned int judgedIndex;
    unsigned int currentTempo;
    unsigned int oldTempo;
    unsigned int lastHakuSector;
    unsigned int nextHakuSector;
    unsigned int lastMeasureSector;
    unsigned int nextMeasureSector;
    short lastJudge[16];
    unsigned int lastJudgeSector[16];
    CDStruct_c6ce2fc0 gameScore;
    unsigned int replaceTable[16];
    _Bool isPerfectMode;
    NSArray *playEventTable;
    NSArray *holdEventTable;
    short *replayJudgeTable;
    short *replayTmpJudgeTable;
    unsigned short _firstMarker;
    unsigned int _currentSector;
    unsigned int _firstMarkerSector;
    double _currentTime;
}

+ (short)rankOfPoint:(unsigned int)arg1;
+ (_Bool)checkExistHoldMarker:(id)arg1;
+ (unsigned int)checkExistHoldMarkerFlag:(id)arg1;
+ (void)getMusicBarData:(char *)arg1 raw:(id)arg2;
@property(readonly, nonatomic) unsigned int firstMarkerSector; // @synthesize firstMarkerSector=_firstMarkerSector;
@property(readonly, nonatomic) unsigned short firstMarker; // @synthesize firstMarker=_firstMarker;
@property(readonly, nonatomic) unsigned int currentSector; // @synthesize currentSector=_currentSector;
@property(readonly, nonatomic) double currentTime; // @synthesize currentTime=_currentTime;
- (void).cxx_destruct;
- (id)getHoldEvents;
- (id)getPlayEvents;
- (void)dealloc;
- (void)judge:(int)arg1 btnPress:(int)arg2;
- (void)addJudge:(short)arg1;
@property(readonly, nonatomic) float playPosition;
@property(readonly, nonatomic) float measurePhase;
@property(readonly, nonatomic) float hakuPhase;
- (const char *)getMusicBar;
- (short)rank;
- (_Bool)isExcellent;
- (_Bool)isFullcombo;
- (const CDStruct_c6ce2fc0 *)getScore;
- (void)getHoldMarkerState:(CDStruct_0f097b75 *)arg1;
- (void)getMarkerState:(int *)arg1;
- (void)seekToTime:(double)arg1;
- (void)reset;
- (void)replay;
- (id)initWithCustomData:(id)arg1 tableData:(id)arg2;
- (id)initWithData:(id)arg1;
- (void)replaceFirstMarker;
- (void)createRandomTable;

@end

